name: second workflow
on:
  push:
  
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_lab
        uses: actions/checkout@v4
      - name: check it runs right
        run: echo "you do it brother"
      #------------------------------------------------------------------
      # setup node.js
      #------------------------------------------------------------------
      - name: setup node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      #------------------------------------------------------------------
      # check node installed 
      #------------------------------------------------------------------
      - name: check node installed background
        run:  |
          echo "node version "
          node -v 
          echo "npm version "
          npm -v 
      #------------------------------------------------------------------
      # check node installed 
      #------------------------------------------------------------------
      - name: creat a script directory background
        run: mkdir -p scripts 
      #------------------------------------------------------------------
      # example in shell based  
      #------------------------------------------------------------------
      - name: example with shell based 
        shell: bash 
        working-directory: scripts
        continue-on-error: true
        env:
          NAME: mohamed 
          CITY: cairo 
        run: | 
            echo "$pwd"
            echo "Bash shell executing..."
            echo "Hello $NAME from $CITY"
            exit 1   # will not break workflow
        
