name: second workflow
on:
  push:
  
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_lab
        uses: actions/checkout@v4
      - name: check it runs right
        run: echo "you do it brother"
      #------------------------------------------------------------------
      # setup node.js
      #------------------------------------------------------------------
      - name: setup node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      #------------------------------------------------------------------
      # check node installed 
      #------------------------------------------------------------------
      - name: check node installed background
        run:  |
          echo "node version "
          node -v 
          echo "npm version "
          npm -v 
          
