name: Variables Demo

on:
  push:

env:
  APP_NAME: workflow-app
  ENVIRONMENT: production
  OWNER: workflow-owner

jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: job-env
      DB_HOST: job-database
      OWNER: job-owner

    steps:
      - name: SHOW JOBS AND WORKFLOW VARIABLES 
        run: |
          echo "APP_NAME=$APP_NAME"
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "DB_HOST=$DB_HOST"
          echo "OWNER=$OWNER"
      - name: step-level-variable
        env:
          OWNER: step-owner #highest periority  
          VERSION: 10.5
        run: |
            echo "owner=$OWNER"
            echo "version=$VERSION"
            echo "app-name=$APP_NAME"
      - name: repo-variables 
        run: |
            echo "API_URL=${{ vars.API_URL }}"
      - name: repo-secret
        run: |
          echo "API_KEY=${{SECRETS.API_KEY}}"
      - name: variables_precedence
        env:
          ENVIRONMENT: step-env
        run: |
          echo "Step-level ENVIRONMENT=$ENVIRONMENT"
          echo "Job-level DB_HOST=$DB_HOST"
          echo "Workflow-level APP_NAME=$APP_NAME"
          echo "OWNER=$OWNER"


      
